#!/bin/bash

export GRROOT_DIR=/shared/storage/physnp/NSCLData/GrROOT6/

export GRROOT_BINDIR=$GRROOT_DIR/bin/
export GRROOT_LIBDIR=$GRROOT_DIR/lib/
export PATH=$PATH:$GRROOT_BINDIR
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$GRROOT_LIBDIR
